---
name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v3
      - uses: j178/prek-action@v1

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup install 1.93.1 && rustup default 1.93.1
      - run: cargo build --verbose
      - run: cargo test --verbose
